name: Backup and Patching Pipeline

on:
  push:
    paths:
      - "ansible/inventory/hosts.ini"

jobs:
  backup-patching:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/site.yml
          inventory: ansible/inventory/hosts.ini
